Mark slice_as_bytes and write_into_slice as unsafe
amethyst/amethyst pull request #2376
Opened 2020-07-19 15:58 UTC by MikailBag

## Description

These functions are not safe: if they are used incorrectly, program's behavior is undefined.
For example [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=73bfe2c72ca24b46a0f212a5791da09c) code fails under MIRI.

## Modifications
This functions are now marked as unsafe.
Please note that PR currently is incomplete: it does not update usages of `write_into_slice` functions.
There are several ways forward:
1) Make those functions safe again, but require that `T: zerocopy::AsBytes`. It will require adding `#[derive(AsBytes)] somewhere.
2) Manually review that all usages are correct, and put `unsafe` blocks where needed.
3) Make `write_into_slice` function take `&mut [MaybeUninit<u8>]` on input. If that slice it later passed to C ffi, it can be sound.

I cannot do the choice, because I know nothing about Amethyst's rendering subsystem.
 

## PR Checklist

By placing an x in the boxes I certify that I have:

- [x] Updated the content of the book if this PR would make the book outdated.
- [ ] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [x] Added unit tests for new code added in this PR.
- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.

If this modified or created any rs files:

- [ ] Ran `cargo +stable fmt --all`
- [ ] Ran `cargo clippy --all --features "empty"`
- [ ] Ran `cargo test --all --features "empty"`

2020-07-30 20:56 UTC, 0x6273 approved these changes

2020-08-05 11:07 UTC, chemicstry requested changes
I'm not sure why this was approved as it is clearly incomplete.

The changes are alright, but I'm not sure what's the best way to handle usage. There aren't many places they are used, so maybe ensuring safety at usage site is the best way to go. Also, this is mostly used for glsl_layout pod types, so maybe a safe impl for these could be done.

2021-01-04 17:42 UTC, jojolepro commented
I think this will require further discussions on how to go forward. @MikailBag would you be willing to lead a discussion on this topic on the forums (community.amethyst.rs)? Thanks!

2021-06-21 13:28 UTC, jojolepro commented
I think we should go with option 2: adding unsafe at the usage point with a comment explaining why. Would you be available to do it? :)

2022-04-18 16:50 UTC, closed without merging