amethyst_core: Reimplement the hide hierarchy system in legion and add unit tests to it
amethyst/amethyst pull request #2538
Opened 2020-12-10 13:24 UTC by grzi

## Description

Re implementation of the hide hierarchy system in legion and unit tests 

## Additions

- Unit tests to validate the system

## Removals

- Spec implementation

## Modifications

- Rename to hide_hierarchy_system 
- Switch to legion

## PR Checklist

By placing an x in the boxes I certify that I have:

- [X] Added unit tests for new code added in this PR.
- [X] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.
- [ ] Added a changelog entry if this will impact users, or modified more than 5 lines of Rust that wasn't a doc comment.
- [ ] Updated the content of the book if this PR would make the book outdated.

If this modified or created any rs files:

- [ ] Ran `cargo +stable fmt --all`
- [ ] Ran `cargo clippy --workspace --features "empty"` (may require `cargo clean` before)
- [ ] Ran `cargo build --features "empty"`
- [ ] Ran `cargo test --workspace --features "empty"`

All of this has been done but due to the legion_v2 state it's actually failing, but not because of my devs

2020-12-10 16:45 UTC, ezpuzz requested changes
Thanks!

2020-12-10 16:45 UTC, ezpuzz commented on amethyst_core/src/lib.rs
> +    hide_hierarchy_system::build,
I don't think this is the namespacing we want to use, probably can remove `::build`

2020-12-10 16:45 UTC, ezpuzz commented on amethyst_core/src/hide_hierarchy_system.rs
> +pub fn build() -> impl Runnable {
This is awesome! Thanks for adding tests 👍🏻   Way better than my attempt in #2536

2020-12-11 16:54 UTC, AlveLarsson commented
Did you check out the LT repo we have? IDK if it's still valid or not or if this transform PR is better?
https://github.com/amethyst/legion_transform (and the readme is outdated)

2020-12-11 17:00 UTC, ezpuzz approved these changes

2020-12-11 17:02 UTC, ezpuzz commented
@AlveLarsson probably would be good to review legion_transform as a possible replacement after we port the existing implementations.  also I don't see anything about managing hidden state in legion_transform.

2020-12-11 17:10 UTC, grzi commented
@AlveLarsson The current system doesn't belong to the transform part IMHO, it's an additional feature specific to amethyst.

Yeah, legion_transform could replace the actual transform module as the code is nearly the same. Maybe as @ezpuzz said, after all the port is done we could 'merge' what has been done on amethyst (if there are) on the legion_transform project and use it as a replacement

2020-12-11 17:10 UTC, AlveLarsson approved these changes
Oh right that wat was what we said, first just a port of the normal transform and after 0.16 the transform repo. Thanks for this! Keep up the great work :)

2020-12-11 17:11 UTC, merged