Fix FpsCounterBundle not inserting FpsCounter
amethyst/amethyst pull request #2620
Opened 2021-01-27 10:48 UTC by LokiVKlokeNaAndoke

## Description

Insert `FpsCounter` resource in `FpsCounterBundle`.

## Motivation and Context

The docs on `FpsCounterBundle` say:
> Automatically adds a FpsCounterSystem __and a FpsCounter resource with the specified sample size__.

(emphasis mine)

This pull request makes the implementation comply with the docs.

## How Has This Been Tested?

```
cargo test --workspace --all-features
```

## Checklist:

- [x] Acknowledged that by making this pull request I release this code under an MIT/Apache 2.0 dual licensing scheme.
- [x] My code follows the code style of this project.
- [ ] If my change required a change to the documentation I have updated the documentation accordingly.
- [ ] I have updated the content of the book if this PR would make the book outdated.
- [ ] I have added tests to cover my changes.
- [ ] My code is used in an example.

2021-01-28 16:09 UTC, ezpuzz commented
@LokiVKlokeNaAndoke could you make the rustdoc comment more clear as to what are reasonable values for the samplesize parameter?  I'm not sure what it should be.

2021-01-28 16:09 UTC, ezpuzz requested changes
needs more docs

2021-01-28 20:16 UTC, LokiVKlokeNaAndoke commented
Neither do I. I just added `new` and `default` to `FpsCounterBundle` just like in `FpsCounter`, and they basically do the same thing. I thought about injecting `FpsCounter` into `FpsCounterBundle`, but it would make the interface too complex.

What about using the builder pattern for this? It would probably make things less confusing.
```rust
///Automatically adds a `FpsCounterSystem` and a [`FpsCounter`] resource with the specified sample size.
#[derive(Default, Debug)]
pub struct FpsCounterBundle {
    samplesize: Option<usize>,
}

impl FpsCounterBundle {
    /// Set the sample size the [`FpsCounter`] uses. The default is 20.
    pub fn sample_size(self, samplesize: usize) -> Self {
        Self {
            samplesize: Some(samplesize),
        }
    }
}
```

instead of

```rust
///Automatically adds a `FpsCounterSystem` and a [`FpsCounter`] resource with the specified sample size.
#[derive(Default, Debug)]
pub struct FpsCounterBundle {
    samplesize: Option<usize>,
}

impl FpsCounterBundle {
    /// Create a new [`FpsCounterBundle`] with the specified sample size. The default is 20, see [`FpsCounter`].
    pub fn new(samplesize: usize) -> Self {
        Self {
            samplesize: Some(samplesize),
        }
    }
}
```

2021-02-05 15:23 UTC, ezpuzz approved these changes

2021-02-05 21:31 UTC, merged